name: publish

on:
  push:
    branches: [master]

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      - uses: pascalgn/npm-publish-action@1.3.8
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^chore: release version (\\S+)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
